### ISSUE TITLE
no rhino shit gif rule

### ISSUE THREAD

**Issue by willn1337** [pajlada/forsen-discord-docs#2]
consider adding "do not post rhino shit gif" to the rules because there is no visible rule but i have been muted for it many times because i did not know it was a rule that you cannot post rhino shit gif ok thanks

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/134767302-1df3d36a-71fa-47f2-b389-67682d68aac1.png)
